### ISSUE TITLE
Is the dataset available?

### ISSUE THREAD

**Issue by daisukelab** [MohammedMosuily/mmlung#1]
Dear author,
Thank you for sharing your work.
Could you make your dataset available as described in the paper?
Thanks again!

**Comment by MohammedMosuily** [comment]
Dear Daisukelab,

Thank you for your interest in our work and for reaching out.

We appreciate your request for access to the dataset. Due to the data and ethical regulations in the United Kingdom, including compliance with GDPR, we are unable to make the dataset publicly available on the web. However, we are happy to provide access upon request to researchers who meet the necessary ethical and data protection requirements.

If you would like to request access, please feel free to contact us directly at mtm1g19@soton.ac.uk with details of your intended use, and we will guide you through the necessary steps.

Thank you again for your understanding and interest in our research.

Best regards,
Mohammed Mosuily
